package code

var en = map[int]string{ //nolint:gosec // 错误文案中的 “token”“password” 字样被误判为硬编码凭据
	ServerError:         "Internal server error",
	Unauthorized:        "Not signed in, or the session has expired",
	CrossOriginRejected: "Cross-site request rejected",

	AlreadyInitialized:    "Already initialized: the administrator account exists",
	SetupCodeInvalid:      "Incorrect setup code",
	UsernameInvalid:       "Username must be 3–32 characters: lowercase letters, digits, . _ -",
	PasswordTooShort:      "Password must be at least 12 characters",
	LoginFailed:           "Incorrect username or password",
	TooManyAttempts:       "Too many attempts. Try again in %d minutes",
	CurrentPasswordWrong:  "Current password is incorrect",
	NotInitialized:        "No administrator yet. Finish first-run setup in the web console",
	SessionRequired:       "This action requires signing in with a browser; API tokens cannot call it",
	PasswordLoginDisabled: "Password sign-in is disabled",
	ReauthPasswordWrong:   "Wrong sign-in password",

	TokenInvalid:       "Invalid token",
	TokenRevoked:       "Token has been revoked",
	TokenExpired:       "Token has expired",
	TokenNameInvalid:   "Name must be 1–64 characters",
	TokenNameDuplicate: "An active token with this name already exists",
	TokenExpiryInvalid: "Validity must be 30 days, 90 days, 1 year or never",
	TokenNotFound:      "Token not found",

	OIDCFieldRequired:              "Display name, issuer, client ID and client secret are required",
	OIDCRedirectInvalid:            "Invalid callback URL",
	OIDCIssuerUnreachable:          "Could not connect to %s: %s",
	OIDCDiscoveryInvalid:           "Invalid OIDC discovery document or issuer mismatch: %s",
	OIDCResetConfirmRequired:       "Changing the issuer or client ID removes the existing binding. Confirm to save",
	OIDCNotConfigured:              "OIDC is not configured",
	OIDCAlreadyBound:               "An OIDC identity is already bound. Unbind it first",
	PasswordLoginDisableNotAllowed: "Bind an OIDC identity and sign in with it once before disabling password sign-in",

	StorageNotFound:              "Storage not found",
	StorageNameInvalid:           "Name must be 1–64 characters",
	StorageNameDuplicate:         "A storage with this name already exists",
	StoragePathRelative:          "The local directory must be an absolute path",
	StorageS3FieldRequired:       "Endpoint, bucket, access key and secret key are required",
	StorageEndpointScheme:        "Leave the protocol out of the endpoint (no http:// or https://); the HTTPS switch decides it",
	StorageLocationInUse:         "This location is already used by storage \"%s\"",
	StorageLocationNotEmpty:      "The location is not empty and is not a kopia repository",
	StorageUnreachable:           "Could not connect: %s",
	StorageNotWritable:           "The location is not writable: %s",
	StorageNotDirectory:          "The path is not a directory: %s",
	StorageNoAccess:              "No permission to access the location: %s",
	StorageBucketNotFound:        "The bucket does not exist",
	StorageAccessDenied:          "Access Denied: wrong access key or secret key, or no permission (%s)",
	StorageKeyRequired:           "Enter the repository key",
	StorageKeyTooShort:           "The password must be at least 12 characters",
	StorageKeyNotConfirmed:       "Confirm that you have saved this key first",
	StorageKeyInvalid:            "Wrong key: it cannot open this repository",
	StorageManagedKeyInvalid:     "The saved key cannot open the repository at this location. Use \"Unlock again\" to provide the right key",
	StorageNotRepository:         "The location is not a kopia repository",
	StorageLocationChangeConfirm: "Changing the storage location needs confirmation",
	StorageAlreadyRepository:     "The location became a kopia repository after the test and was left untouched. Test the connection again",
	StorageReauthRequired:        "Verify your identity first",
	StorageDirNameInvalid:        "The folder name cannot be empty or contain /",
	StorageDirExists:             "A folder with this name already exists",
	StorageDirNoPermission:       "No write permission to create a folder here",
	StorageDirNoAccess:           "No permission to open this directory",
	StorageDirCreateFailed:       "Could not create the folder: %s",
	StorageInUse:                 "The storage is still referenced by jobs and cannot be deleted: %s",
	StorageLocationLocked:        "The storage is still referenced by jobs and its location cannot be changed: %s",

	ChannelNotFound:             "Channel not found",
	ChannelNameInvalid:          "Name must be 1–64 characters",
	ChannelNameDuplicate:        "A channel with this name already exists",
	ChannelHostRequired:         "Enter the host",
	ChannelPortInvalid:          "Port must be between 1 and 65535",
	ChannelUserRequired:         "Enter the SSH username",
	ChannelAuthMethodInvalid:    "Authentication must be password or private key",
	ChannelPasswordRequired:     "Enter the password",
	ChannelPrivateKeyRequired:   "Provide the private key",
	ChannelSOCKS5CredentialPair: "Fill in both the SOCKS5 username and password, or neither",
	ChannelPassphraseMissing:    "The private key is encrypted. Enter its passphrase",
	ChannelPassphraseWrong:      "Wrong passphrase for the private key",
	ChannelKeyInvalid:           "Unrecognized private key. OpenSSH and PEM RSA, ECDSA and Ed25519 keys are supported",
	ChannelViaNotFound:          "The channel to route through does not exist",
	ChannelViaCycle:             "A channel cannot route through itself or through a channel that would form a loop",
	ChannelChainTooLong:         "A chain can have at most 5 hops; this one has %d",
	ChannelHopFailed:            "Hop %d %s (%s): %s",
	ChannelHostKeyChanged:       "Hop %d %s (%s): the host key has changed. Re-confirm that channel's host key first",
	ChannelInUse:                "The channel is still in use and cannot be deleted: %s",
	ChannelNotSSH:               "Only SSH jump host channels have a host key",
	ChannelReasonUnreachable:    "could not connect (%s)",
	ChannelReasonTimeout:        "connection timed out",
	ChannelReasonCanceled:       "canceled",
	ChannelReasonProtocol:       "protocol error (%s)",
	ChannelReasonNegotiation:    "method negotiation failed (%s)",
	ChannelReasonAuthFailed:     "authentication failed",
	ChannelReasonHostKeyUnknown: "host key not confirmed",
	ChannelReasonHostKeyChanged: "host key has changed",

	DataSourceNotFound:           "Data source not found",
	DataSourceNameInvalid:        "Name must be 1–64 characters",
	DataSourceNameDuplicate:      "A data source with this name already exists",
	DataSourceHostRequired:       "Enter the host",
	DataSourcePortInvalid:        "Port must be between 1 and 65535",
	DataSourceUserRequired:       "Enter the username",
	DataSourceAuthMethodInvalid:  "Authentication must be password or private key",
	DataSourcePasswordRequired:   "Enter the password",
	DataSourcePrivateKeyRequired: "Provide the private key",
	DataSourcePassphraseMissing:  "The private key is encrypted. Enter its passphrase",
	DataSourcePassphraseWrong:    "Wrong passphrase for the private key",
	DataSourceKeyInvalid:         "Unrecognized private key. OpenSSH and PEM RSA, ECDSA and Ed25519 keys are supported",
	DataSourceTLSPairRequired:    "Provide both the client certificate and the client key, or neither",
	DataSourceCAInvalid:          "Could not parse the CA certificate (PEM required)",
	DataSourceClientCertInvalid:  "Could not parse the client certificate (PEM required)",
	DataSourceClientKeyInvalid:   "Could not parse the client key (PEM required), or it does not match the client certificate",
	DataSourceChannelNotFound:    "The selected network channel does not exist",
	DataSourceConfigInvalid:      "Invalid data source settings",
	DataSourceTestFailed:         "Hop %d %s (%s): %s",
	DataSourceNotServerFile:      "Only server file data sources have a target host key",
	DataSourceReasonUnreachable:  "could not connect (%s)",
	DataSourceReasonTimeout:      "connection timed out",
	DataSourceReasonCanceled:     "canceled",
	DataSourceReasonAuthFailed:   "authentication failed (%s)",
	DataSourceReasonTLS:          "TLS handshake failed (%s)",
	DataSourceReasonCertificate:  "certificate verification failed (%s)",
	DataSourceReasonFailed:       "%s",
	DataSourceDatabasesFailed:    "Could not read the database list: %s",
	DataSourceInUse:              "The data source is still referenced by jobs and cannot be deleted: %s",

	JobNotFound:               "Job not found",
	JobNameInvalid:            "Job name must be 1–64 characters",
	JobNameDuplicate:          "A job with this name already exists",
	JobTypeUnsupported:        "Only backup jobs are supported in this version",
	JobDataSourceNotFound:     "The selected data source does not exist",
	JobDataSourceUnsupported:  "Only MySQL and PostgreSQL data sources are supported in this version",
	JobDataSourceNotReady:     "The data source status is not OK. Test its connection first",
	JobStorageNotFound:        "The selected storage does not exist",
	JobStorageNotReady:        "The storage status is not OK. Test its connection first",
	JobScopeInvalid:           "Scope must be the whole instance or selected databases",
	JobDatabasesRequired:      "Select at least one database",
	JobMethodUnsupported:      "Only full backups are supported in this version",
	JobExcludeInvalid:         "Invalid excluded table: %s (MySQL: db.table, PostgreSQL: db.schema.table)",
	JobPrefixInvalid:          "Path prefix must be 1–128 letters, digits or ._-/, must not start or end with /, and must not contain .. or //",
	JobPrefixConflict:         "Path prefix duplicates or nests with job \"%s\" in the same storage",
	JobCompressionInvalid:     "Compression must be none, gzip or zstd",
	JobScheduleInvalid:        "Invalid schedule: %[2]s", // 参数依次为中文、英文原因
	JobTimezoneInvalid:        "Not a valid IANA time zone",
	JobRetentionDaysInvalid:   "Days to keep must be between 1 and 365",
	JobRetentionWeeksInvalid:  "Weeks to keep must be between 0 and 520",
	JobRetentionMonthsInvalid: "Months to keep must be between 0 and 120",
	JobRetriesInvalid:         "Retries must be between 0 and 5",
	JobRetryIntervalInvalid:   "Retry interval must be between 1 and 120 minutes",
	JobTimeoutInvalid:         "Timeout must be between 10 minutes and 48 hours",
	JobImmutableField:         "Data source, storage and path prefix cannot change after creation. Create a new job instead",
	JobRunActive:              "The job is running or queued. Cancel it before deleting",
	JobSnapshotsNotDeleted:    "Job deleted, but %d snapshots could not be deleted. Remove them with the kopia CLI",
	JobSnapshotsUnreachable:   "Job deleted, but its storage could not be opened, so its snapshots were not deleted. Remove them with the kopia CLI",
	JobRunAlreadyActive:       "The job is already running or queued",
	JobRunNotFound:            "Run not found",
	JobRunFinished:            "The run has already finished and cannot be canceled",
	JobStatsStorageUnreadable: "Could not read snapshots from the storage. Check the storage status",
	JobReasonStillRunning:     "The previous run is still running",
	JobReasonRetryVoided:      "Retry voided: the next scheduled run is due",
	JobReasonInterrupted:      "OpsNap restarted; the run was interrupted",
	JobReasonRestart:          "OpsNap restarted",
	JobReasonTimeout:          "Timed out (exceeded %s)",
	JobDurationMinutes:        "%d min",
	JobDurationHours:          "%d h",
	JobDurationHoursMinutes:   "%d h %d min",

	JobSnapshotsUnreachableCount: "Job deleted, but its storage could not be opened, so its %d snapshots were not deleted. Remove them with the kopia CLI",

	Language:                    "en",
	ListSep:                     ", ",
	WrapColon:                   "%s: %s",
	WrapFullColon:               "%s: %s",
	RunLogPrepare:               "Checking storage, data source and export tools",
	RunStorageMissing:           "The storage does not exist",
	RunStorageNotOK:             "The status of storage \"%s\" is not \"OK\" (%s). Test the storage connection first",
	RunDataSourceMissing:        "The data source does not exist",
	RunHostKeyChanged:           "A host key on the network path of data source \"%s\" has changed. Confirm the new host key on the Data Sources page first",
	RunLogToolPath:              "Export tool %s: %s",
	RunOpenStorageFailed:        "Failed to open storage \"%s\": %s",
	RunLogStorageOpened:         "Opened storage \"%s\"",
	RunLogConnecting:            "Connecting to data source \"%s\" (%s:%d) through the network channel",
	RunConnectFailed:            "Failed to connect to the data source: %s",
	RunLogConnected:             "Connected, server version %s",
	RunListDatabasesFailed:      "Failed to list the databases in the instance: %s",
	RunNoDatabases:              "The instance has no databases to export",
	RunMissingDatabases:         "The selected databases do not exist in the data source (or do not allow connections): %s",
	RunLogDatabases:             "Databases to export: %s",
	RunStartDumpFailed:          "Failed to prepare the export: %s",
	RunLogForwarding:            "Opened a temporary port on 127.0.0.1; the export tools connect to the data source through it and the network path",
	RunLogExporting:             "Exporting and streaming into the repository, path prefix %s, compression %s",
	RunLogExportChecked:         "All export tools exited normally and the export passed the integrity checks",
	RunLogFileSize:              "%s: %d bytes",
	RunLogSnapshotVerified:      "Snapshot %s written and verified by reading it back: %d files, %d bytes in total, %d bytes newly uploaded",
	RunLogListSnapshotsFailed:   "Failed to read this job's snapshots; the retention policy is not applied this time: %s",
	RunLogRetention:             "Retention: last %d days, %d weeks, %d months; this job has %d snapshots, keeping %d, deleting %d",
	RunLogDeleteFailed:          "Failed to delete expired snapshots (this run still succeeded): %s",
	RunLogDeleted:               "Deleted %d expired snapshots; starting quick maintenance",
	RunLogMaintainFailed:        "Quick maintenance failed (this run still succeeded): %s",
	RunLogMaintained:            "Quick maintenance finished; deleted data is freed by the next full maintenance",
	RunLogCanceled:              "Run canceled: stopped the export tools, closed the port forwarding and deleted the temporary files; no snapshot was created",
	RunLogAborted:               "%s: stopped the export tools; no snapshot was created",
	RunReasonEllipsis:           "...",
	DumpErrInvalidOptions:       "Invalid export options",
	DumpErrToolNotFound:         "Export tool not found",
	DumpErrToolVersion:          "Export tool version is too old",
	DumpErrUnsupportedTLS:       "The export tool cannot connect with the data source's TLS settings",
	DumpErrPrivilege:            "The data source account lacks privileges",
	DumpErrIncomplete:           "The export is incomplete",
	DumpErrClosed:               "The export was stopped",
	DumpToolFailed:              "%s failed (exit code %d)",
	DumpStderrOmitted:           "(the first %d bytes of error output were omitted)",
	DumpViaChannelFailed:        "; connecting to the data source through the network path failed: %s",
	DumpUnsupportedType:         "%s: exporting data sources of type %q is not supported",
	DumpNoDialer:                "%s: missing network path",
	DumpNoDatabases:             "%s: select at least one database",
	DumpEmptyDatabase:           "%s: empty database name",
	DumpGlobalsPGOnly:           "%s: global objects apply only to PostgreSQL",
	DumpMySQLOnlyOptions:        "%s: accounts and privileges, routines, triggers and events apply only to MySQL",
	DumpExcludeFormat:           "%s: exclusion rule %q must be written as %s",
	DumpExcludeFormatMySQL:      "database.table",
	DumpExcludeFormatPG:         "database.schema.table",
	DumpToolMissing:             "%s: %s (looked in PATH, then in the directory set by the tools.dir option). Fix: install %s on the OpsNap host, or put %s in tools.dir",
	DumpPkgMySQL:                "the MySQL client",
	DumpPkgPostgreSQL:           "the PostgreSQL client",
	DumpToolVersionUnknown:      "Could not determine the version of %s (%s): %s",
	DumpConnect:                 "Connecting to the data source: %s",
	DumpNoSystemCA:              "%s: no system CA bundle was found, so the export tool cannot verify the server certificate. Fix: provide a CA certificate in the data source's TLS settings",
	DumpStartTool:               "Starting %s: %s",
	DumpReadOutput:              "Reading the output of %s: %s",
	DumpGlobalsSuperuser:        "%s: exporting global objects requires superuser privileges (pg_dumpall reads pg_authid): %s",
	DumpIncompleteMySQL:         "%s: the mysqldump output does not end with the completion marker (-- Dump completed)",
	DumpIncompletePGArchive:     "%s: the pg_dump output does not start with a complete custom-format archive header",
	DumpIncompletePGGlobals:     "%s: the pg_dumpall output has no completion marker (PostgreSQL database cluster dump complete)",
	DumpMariaDBTLS:              "%s: the mysqldump on the OpsNap host comes from MariaDB (%s); it falls back to plain text when the server does not support TLS and can only verify the certificate together with the host name, so it cannot guarantee the data source's TLS mode %q. Fix: provide the official MySQL mysqldump in PATH or tools.dir",
	DumpMySQLDumpOlder:          "mysqldump %d.%d is older than the server (%d.%d); exporting anyway. If the export fails, provide a mysqldump no older than the server in PATH or tools.dir",
	DumpVerifyCAOnly:            "mysqldump connects through a local port forward and cannot verify the server certificate's host name, so only the CA is verified this time; the host name was verified when OpsNap connected to the data source through the same path",
	DumpListTables:              "Listing the tables to export: %s",
	DumpNonInnoDB:               "The following %d tables are not InnoDB, so their export is not guaranteed to be consistent with the other tables: %s",
	DumpExcludeUnmatched:        "Exclusion rule %s matched no tables",
	DumpAccounts:                "Exporting accounts and privileges: %s",
	DumpAccountsPrivilege:       "%s: exporting accounts and privileges requires reading the mysql system schema (%s). Fix: GRANT SELECT ON mysql.* TO '%s'@'%s';",
	DumpPGToolTooOld:            "%s: %s major version %d is older than the server's %d. Fix: install the PostgreSQL %d client or newer on the OpsNap host, in PATH or tools.dir",
	DumpPGPasswordNewline:       "%s: the password contains a line break and cannot be written to pg_dump's password file",
	DumpCheckExclude:            "Checking exclusion rule %s: %s",
	KopiaErrInvalidSnapshot:     "Invalid snapshot request",
	KopiaErrVerify:              "Verifying the snapshot by reading it back",
	KopiaErrNotJobSnapshot:      "The snapshot does not exist or does not belong to this job",
	KopiaUnsupportedCompression: "%s: unsupported compression %q",
	KopiaNoPrefix:               "%s: missing path prefix",
	KopiaNoFiles:                "%s: no files",
	KopiaBadFileName:            "%s: invalid file name %q",
	KopiaDupFileName:            "%s: duplicate file name %q",
	KopiaNoReader:               "%s: file %q has no content",
	KopiaWriteSnapshot:          "Writing the snapshot: %s",
	KopiaWriteIncomplete:        "Writing the snapshot did not finish: %s",
	KopiaWriteFatal:             "Writing the snapshot failed: %d files had errors",
	KopiaSaveManifest:           "Saving the snapshot manifest: %s",
	KopiaVerifyDeleteFailed:     "%s: %s (deleting the manifest also failed: %s)",
	KopiaRootNotDir:             "The snapshot root is not a directory",
	KopiaReadDir:                "Reading the snapshot directory: %s",
	KopiaFileCount:              "The snapshot has %d files; expected %d",
	KopiaFileMissing:            "File %s is missing from the snapshot",
	KopiaFileSize:               "File %s is %d bytes; expected %d",
	KopiaFileNoObject:           "File %s has no content ID",
	KopiaFileIncomplete:         "The content of file %s is incomplete: %s",
	KopiaListSnapshots:          "Listing snapshots: %s",
	KopiaLoadManifests:          "Reading snapshot manifests: %s",
	KopiaDeleteSnapshots:        "Deleting snapshots: %s",
	KopiaMaintainMode:           "Unsupported maintenance mode %q",
	KopiaMaintainUnsupported:    "The repository connection does not support maintenance",
	KopiaMaintain:               "Repository maintenance (%s): %s",
	NetErrTooManyHops:           "The network path has more than 5 hops",
	NetErrCycle:                 "The network path has a cycle",
	NetErrInvalidHop:            "Incomplete channel settings",
	NetErrAuthFailed:            "Authentication failed",
	NetErrNegotiation:           "SOCKS5 method negotiation failed",
	NetErrProtocol:              "Protocol error",
	NetErrHostKeyUnknown:        "Host key not confirmed",
	NetErrHostKeyChanged:        "Host key has changed",
	NetErrPassphraseMissing:     "The private key is encrypted and no passphrase was given",
	NetErrPassphraseWrong:       "Wrong private key passphrase",
	NetErrKeyInvalid:            "Unrecognized private key format",
	NetHopFailed:                "Hop %d %s (%s): %s",
	NetHostKeyChangedDetail:     "%s: saved %s, now presented %s %s",
	NetHostKeyUnknownDetail:     "%s: %s %s",
	NetTimeout:                  "Connection timed out: %s",
	NetCanceled:                 "Canceled: %s",
	NetSSHHandshake:             "%s: SSH handshake failed: %s",
	NetSocksNetwork:             "SOCKS5 does not support %s",
	NetSocksClosed:              "%s: the proxy closed the connection",
	NetSocksNotSocks:            "%s: the peer is not a SOCKS5 proxy",
	NetSocksAuthRequired:        "%s: the proxy requires authentication",
	NetSocksNoUserPass:          "%s: the proxy does not accept username/password authentication",
	NetSocksBadMethod:           "%s: the proxy chose authentication method %d, which was not offered",
	NetSocksCredTooLong:         "%s: the username or password is longer than 255 bytes",
	NetSocksReply1:              "internal proxy error",
	NetSocksReply2:              "not allowed by the proxy's rules",
	NetSocksReply3:              "network unreachable",
	NetSocksReply4:              "host unreachable",
	NetSocksReply5:              "connection refused",
	NetSocksReply6:              "TTL expired",
	NetSocksReply7:              "the proxy does not support CONNECT",
	NetSocksReply8:              "the proxy does not support this address type",
	NetSocksReplyCode:           "error code %d",
	NetSocksBadPort:             "Invalid port %q",
	NetSocksHostTooLong:         "The host name is longer than 255 bytes",
	NetSocksBadReply:            "%s: invalid CONNECT reply",
	NetSocksConnectFailed:       "The SOCKS5 proxy could not connect to %s: %s",
	NetSocksBadAddrType:         "%s: invalid address type in the CONNECT reply",
	NetUnknownKind:              "%s: unknown type %q",
	NetNoHost:                   "%s: missing host",
	NetBadPort:                  "%s: port %d is outside 1–65535",
	NetNoSSHUser:                "%s: missing SSH user name",
	NetSSHAuthRequired:          "%s: SSH authentication needs a password or a private key",
	NetHopCount:                 "%s: %d hops",
	NetChannelTwice:             "%s: channel %s appears twice",
	NetHopInvalid:               "Hop %d %s: %s",
	NetDialFailed:               "Failed to connect to %s: %s",
	NetNotSSHTarget:             "%s: the target is not an SSH host",
	ConnErrInvalidConfig:        "Invalid data source settings",
	ConnNoUser:                  "%s: missing user name",
	ConnUnknownTLSMode:          "%s: unknown TLS mode",
	ConnCANotPEM:                "Could not parse the CA certificate (PEM format required)",
	ConnCertNotPEM:              "Could not parse the client certificate (PEM format required)",
	ConnKeyInvalid:              "Could not parse the client private key (PEM format required)",
	ConnKeyMismatch:             "The client private key does not match the certificate",
	ConnCertMissing:             "A client private key was given; the client certificate is also required",
	ConnKeyMissing:              "A client certificate was given; the client private key is also required",
	ConnNoPeerCert:              "The server presented no certificate",
	WrapParen:                   "%s (%s)",
	KopiaErrInvalidPassword:     "The key is incorrect and cannot open this repository",
	KopiaErrNotEmpty:            "The target location is not empty and is not a kopia repository",
	KopiaErrAlreadyRepository:   "The target location is already a kopia repository",
	KopiaErrNotRepository:       "The target location is not a kopia repository",
	KopiaCreate:                 "Creating the kopia repository: %s",
	KopiaConnect:                "Connecting to the kopia repository: %s",
	KopiaNotDirectory:           "%s is not a directory",
	KopiaErrRelativePath:        "The local directory must be an absolute path",
	KopiaErrEndpointScheme:      "The endpoint must not include a scheme (remove http:// or https://)",
	KopiaErrUnknownKind:         "Unknown storage type",
	KopiaGenerateKey:            "Generating the repository key: %s",
	KopiaErrInvalidDirName:      "The folder name must not be empty or contain /",
	KopiaReadSnapshot:           "Reading snapshot %s: %s",
	KopiaUsage:                  "Calculating snapshot usage: %s",
	StorageErrNotReady:          "The storage status is not OK",
	SecretErrInvalidKey:         "Invalid master key format: 32 random bytes encoded in base64 are required",
	SecretErrDecrypt:            "Decryption failed: the ciphertext is corrupted or the master key does not match",
	SecretGenerateKey:           "Generating the master key: %s",
	SecretInitCipher:            "Initializing encryption: %s",
	SecretRandom:                "Generating random bytes: %s",
	SecretErrKeyMissing:         "The master key is missing",
	SecretErrKeyMismatch:        "The master key does not match the database",
	SecretErrNotInitialized:     "The master key is not initialized yet",
	ProbeVersionUnrecognized:    "Could not recognize a version number in %q",
	DataSourceListUnsupported:   "Listing databases is not supported for data source type %q",
}
