package code

var en = map[int]string{ //nolint:gosec // 错误文案中的 “token”“password” 字样被误判为硬编码凭据
	ServerError:         "Internal server error",
	Unauthorized:        "Not signed in, or the session has expired",
	CrossOriginRejected: "Cross-site request rejected",

	AlreadyInitialized:    "Already initialized: the administrator account exists",
	SetupCodeInvalid:      "Incorrect setup code",
	UsernameInvalid:       "Username must be 3–32 characters: lowercase letters, digits, . _ -",
	PasswordTooShort:      "Password must be at least 12 characters",
	LoginFailed:           "Incorrect username or password",
	TooManyAttempts:       "Too many attempts. Try again in %d minutes",
	CurrentPasswordWrong:  "Current password is incorrect",
	NotInitialized:        "No administrator yet. Finish first-run setup in the web console",
	SessionRequired:       "This action requires signing in with a browser; API tokens cannot call it",
	PasswordLoginDisabled: "Password sign-in is disabled",
	ReauthPasswordWrong:   "Wrong sign-in password",

	TokenInvalid:       "Invalid token",
	TokenRevoked:       "Token has been revoked",
	TokenExpired:       "Token has expired",
	TokenNameInvalid:   "Name must be 1–64 characters",
	TokenNameDuplicate: "An active token with this name already exists",
	TokenExpiryInvalid: "Validity must be 30 days, 90 days, 1 year or never",
	TokenNotFound:      "Token not found",

	OIDCFieldRequired:              "Display name, issuer, client ID and client secret are required",
	OIDCRedirectInvalid:            "Invalid callback URL",
	OIDCIssuerUnreachable:          "Could not connect to %s: %s",
	OIDCDiscoveryInvalid:           "Invalid OIDC discovery document or issuer mismatch: %s",
	OIDCResetConfirmRequired:       "Changing the issuer or client ID removes the existing binding. Confirm to save",
	OIDCNotConfigured:              "OIDC is not configured",
	OIDCAlreadyBound:               "An OIDC identity is already bound. Unbind it first",
	PasswordLoginDisableNotAllowed: "Bind an OIDC identity and sign in with it once before disabling password sign-in",

	StorageNotFound:              "Storage not found",
	StorageNameInvalid:           "Name must be 1–64 characters",
	StorageNameDuplicate:         "A storage with this name already exists",
	StoragePathRelative:          "The local directory must be an absolute path",
	StorageS3FieldRequired:       "Endpoint, bucket, access key and secret key are required",
	StorageEndpointScheme:        "Leave the protocol out of the endpoint (no http:// or https://); the HTTPS switch decides it",
	StorageLocationInUse:         "This location is already used by storage \"%s\"",
	StorageLocationNotEmpty:      "The location is not empty and is not a kopia repository",
	StorageUnreachable:           "Could not connect: %s",
	StorageNotWritable:           "The location is not writable: %s",
	StorageNotDirectory:          "The path is not a directory: %s",
	StorageNoAccess:              "No permission to access the location: %s",
	StorageBucketNotFound:        "The bucket does not exist",
	StorageAccessDenied:          "Access Denied: wrong access key or secret key, or no permission (%s)",
	StorageKeyRequired:           "Enter the repository key",
	StorageKeyTooShort:           "The password must be at least 12 characters",
	StorageKeyNotConfirmed:       "Confirm that you have saved this key first",
	StorageKeyInvalid:            "Wrong key: it cannot open this repository",
	StorageManagedKeyInvalid:     "The saved key cannot open the repository at this location. Use \"Unlock again\" to provide the right key",
	StorageNotRepository:         "The location is not a kopia repository",
	StorageLocationChangeConfirm: "Changing the storage location needs confirmation",
	StorageAlreadyRepository:     "The location became a kopia repository after the test and was left untouched. Test the connection again",
	StorageReauthRequired:        "Verify your identity first",
	StorageDirNameInvalid:        "The folder name cannot be empty or contain /",
	StorageDirExists:             "A folder with this name already exists",
	StorageDirNoPermission:       "No write permission to create a folder here",
	StorageDirNoAccess:           "No permission to open this directory",
	StorageDirCreateFailed:       "Could not create the folder: %s",

	ChannelNotFound:             "Channel not found",
	ChannelNameInvalid:          "Name must be 1–64 characters",
	ChannelNameDuplicate:        "A channel with this name already exists",
	ChannelHostRequired:         "Enter the host",
	ChannelPortInvalid:          "Port must be between 1 and 65535",
	ChannelUserRequired:         "Enter the SSH username",
	ChannelAuthMethodInvalid:    "Authentication must be password or private key",
	ChannelPasswordRequired:     "Enter the password",
	ChannelPrivateKeyRequired:   "Provide the private key",
	ChannelSOCKS5CredentialPair: "Fill in both the SOCKS5 username and password, or neither",
	ChannelPassphraseMissing:    "The private key is encrypted. Enter its passphrase",
	ChannelPassphraseWrong:      "Wrong passphrase for the private key",
	ChannelKeyInvalid:           "Unrecognized private key. OpenSSH and PEM RSA, ECDSA and Ed25519 keys are supported",
	ChannelViaNotFound:          "The channel to route through does not exist",
	ChannelViaCycle:             "A channel cannot route through itself or through a channel that would form a loop",
	ChannelChainTooLong:         "A chain can have at most 5 hops; this one has %d",
	ChannelHopFailed:            "Hop %d %s (%s): %s",
	ChannelHostKeyChanged:       "Hop %d %s (%s): the host key has changed. Re-confirm that channel's host key first",
	ChannelInUse:                "The channel is still in use and cannot be deleted: %s",
	ChannelNotSSH:               "Only SSH jump host channels have a host key",
	ChannelReasonUnreachable:    "could not connect (%s)",
	ChannelReasonTimeout:        "connection timed out",
	ChannelReasonCanceled:       "canceled",
	ChannelReasonProtocol:       "protocol error (%s)",
	ChannelReasonNegotiation:    "method negotiation failed (%s)",
	ChannelReasonAuthFailed:     "authentication failed",
	ChannelReasonHostKeyUnknown: "host key not confirmed",
	ChannelReasonHostKeyChanged: "host key has changed",
}
