package code

var zhCN = map[int]string{ //nolint:gosec // 错误文案中的“密码”字样被误判为硬编码凭据
	ServerError:         "服务器内部错误",
	Unauthorized:        "未登录或登录已过期",
	CrossOriginRejected: "跨站请求被拒绝",

	AlreadyInitialized:    "已初始化：管理员账号已存在",
	SetupCodeInvalid:      "设置码不正确",
	UsernameInvalid:       "用户名须为 3–32 个字符，只能包含小写字母、数字以及 . _ -",
	PasswordTooShort:      "密码至少需要 12 个字符",
	LoginFailed:           "用户名或密码错误",
	TooManyAttempts:       "尝试次数过多，请在 %d 分钟后重试",
	CurrentPasswordWrong:  "当前密码不正确",
	NotInitialized:        "尚未创建管理员，请通过网页完成首次设置",
	SessionRequired:       "该操作只能在浏览器登录后进行，API 令牌无权调用",
	PasswordLoginDisabled: "密码登录已关闭",
	ReauthPasswordWrong:   "登录密码不正确",

	TokenInvalid:       "令牌无效",
	TokenRevoked:       "令牌已吊销",
	TokenExpired:       "令牌已过期",
	TokenNameInvalid:   "名称须为 1–64 个字符",
	TokenNameDuplicate: "已有同名的有效令牌",
	TokenExpiryInvalid: "有效期只能是 30 天、90 天、1 年或永不过期",
	TokenNotFound:      "令牌不存在",

	OIDCFieldRequired:              "显示名称、Issuer、Client ID 与 Client Secret 均为必填",
	OIDCRedirectInvalid:            "回调地址无效",
	OIDCIssuerUnreachable:          "无法连接 %s：%s",
	OIDCDiscoveryInvalid:           "OIDC discovery 文档无效或 Issuer 不一致：%s",
	OIDCResetConfirmRequired:       "修改 Issuer 或 Client ID 会清除已有绑定，请确认后再保存",
	OIDCNotConfigured:              "尚未配置 OIDC",
	OIDCAlreadyBound:               "已绑定 OIDC 身份，请先解除当前绑定",
	PasswordLoginDisableNotAllowed: "需要先绑定 OIDC 身份，并用它成功登录一次，才能关闭密码登录",

	StorageNotFound:              "存储不存在",
	StorageNameInvalid:           "名称须为 1–64 个字符",
	StorageNameDuplicate:         "已有同名的存储",
	StoragePathRelative:          "本地目录必须是绝对路径",
	StorageS3FieldRequired:       "Endpoint、Bucket、Access Key 与 Secret Key 均为必填",
	StorageEndpointScheme:        "Endpoint 不含协议，去掉 http:// 或 https://，是否使用 HTTPS 由开关决定",
	StorageLocationInUse:         "该位置已被存储「%s」使用",
	StorageLocationNotEmpty:      "目标位置不为空，且不是 kopia 仓库",
	StorageUnreachable:           "无法连接：%s",
	StorageNotWritable:           "目标位置不可写：%s",
	StorageNotDirectory:          "路径不是目录：%s",
	StorageNoAccess:              "无权访问目标位置：%s",
	StorageBucketNotFound:        "Bucket 不存在",
	StorageAccessDenied:          "Access Denied：Access Key 或 Secret Key 不正确，或没有权限（%s）",
	StorageKeyRequired:           "请提供仓库密钥",
	StorageKeyTooShort:           "密码至少需要 12 个字符",
	StorageKeyNotConfirmed:       "请先确认已保存这把密钥",
	StorageKeyInvalid:            "密钥不正确，无法解开这个仓库",
	StorageManagedKeyInvalid:     "保存的密钥无法打开该位置的仓库，请用“重新解锁”提供正确的密钥",
	StorageNotRepository:         "目标位置不是 kopia 仓库",
	StorageLocationChangeConfirm: "更改存储位置需要确认",
	StorageAlreadyRepository:     "目标位置在测试之后已变成 kopia 仓库，没有覆盖它；请重新测试连接",
	StorageReauthRequired:        "请先验证身份",
	StorageDirNameInvalid:        "文件夹名称不能为空，也不能包含 /",
	StorageDirExists:             "已有同名的文件夹",
	StorageDirNoPermission:       "没有写权限，无法在这里新建文件夹",
	StorageDirNoAccess:           "无权访问这个目录",
	StorageDirCreateFailed:       "新建文件夹失败：%s",
}
