package code

var zhCN = map[int]string{ //nolint:gosec // 错误文案中的“密码”字样被误判为硬编码凭据
	ServerError:         "服务器内部错误",
	Unauthorized:        "未登录或登录已过期",
	CrossOriginRejected: "跨站请求被拒绝",

	AlreadyInitialized:    "已初始化：管理员账号已存在",
	SetupCodeInvalid:      "设置码不正确",
	UsernameInvalid:       "用户名须为 3–32 个字符，只能包含小写字母、数字以及 . _ -",
	PasswordTooShort:      "密码至少需要 12 个字符",
	LoginFailed:           "用户名或密码错误",
	TooManyAttempts:       "尝试次数过多，请在 %d 分钟后重试",
	CurrentPasswordWrong:  "当前密码不正确",
	NotInitialized:        "尚未创建管理员，请通过网页完成首次设置",
	SessionRequired:       "该操作只能在浏览器登录后进行，API 令牌无权调用",
	PasswordLoginDisabled: "密码登录已关闭",
	ReauthPasswordWrong:   "登录密码不正确",

	TokenInvalid:       "令牌无效",
	TokenRevoked:       "令牌已吊销",
	TokenExpired:       "令牌已过期",
	TokenNameInvalid:   "名称须为 1–64 个字符",
	TokenNameDuplicate: "已有同名的有效令牌",
	TokenExpiryInvalid: "有效期只能是 30 天、90 天、1 年或永不过期",
	TokenNotFound:      "令牌不存在",

	OIDCFieldRequired:              "显示名称、Issuer、Client ID 与 Client Secret 均为必填",
	OIDCRedirectInvalid:            "回调地址无效",
	OIDCIssuerUnreachable:          "无法连接 %s：%s",
	OIDCDiscoveryInvalid:           "OIDC discovery 文档无效或 Issuer 不一致：%s",
	OIDCResetConfirmRequired:       "修改 Issuer 或 Client ID 会清除已有绑定，请确认后再保存",
	OIDCNotConfigured:              "尚未配置 OIDC",
	OIDCAlreadyBound:               "已绑定 OIDC 身份，请先解除当前绑定",
	PasswordLoginDisableNotAllowed: "需要先绑定 OIDC 身份，并用它成功登录一次，才能关闭密码登录",

	StorageNotFound:              "存储不存在",
	StorageNameInvalid:           "名称须为 1–64 个字符",
	StorageNameDuplicate:         "已有同名的存储",
	StoragePathRelative:          "本地目录必须是绝对路径",
	StorageS3FieldRequired:       "Endpoint、Bucket、Access Key 与 Secret Key 均为必填",
	StorageEndpointScheme:        "Endpoint 不含协议，去掉 http:// 或 https://，是否使用 HTTPS 由开关决定",
	StorageLocationInUse:         "该位置已被存储「%s」使用",
	StorageLocationNotEmpty:      "目标位置不为空，且不是 kopia 仓库",
	StorageUnreachable:           "无法连接：%s",
	StorageNotWritable:           "目标位置不可写：%s",
	StorageNotDirectory:          "路径不是目录：%s",
	StorageNoAccess:              "无权访问目标位置：%s",
	StorageBucketNotFound:        "Bucket 不存在",
	StorageAccessDenied:          "Access Denied：Access Key 或 Secret Key 不正确，或没有权限（%s）",
	StorageKeyRequired:           "请提供仓库密钥",
	StorageKeyTooShort:           "密码至少需要 12 个字符",
	StorageKeyNotConfirmed:       "请先确认已保存这把密钥",
	StorageKeyInvalid:            "密钥不正确，无法解开这个仓库",
	StorageManagedKeyInvalid:     "保存的密钥无法打开该位置的仓库，请用“重新解锁”提供正确的密钥",
	StorageNotRepository:         "目标位置不是 kopia 仓库",
	StorageLocationChangeConfirm: "更改存储位置需要确认",
	StorageAlreadyRepository:     "目标位置在测试之后已变成 kopia 仓库，没有覆盖它；请重新测试连接",
	StorageReauthRequired:        "请先验证身份",
	StorageDirNameInvalid:        "文件夹名称不能为空，也不能包含 /",
	StorageDirExists:             "已有同名的文件夹",
	StorageDirNoPermission:       "没有写权限，无法在这里新建文件夹",
	StorageDirNoAccess:           "无权访问这个目录",
	StorageDirCreateFailed:       "新建文件夹失败：%s",

	ChannelNotFound:             "通道不存在",
	ChannelNameInvalid:          "名称须为 1–64 个字符",
	ChannelNameDuplicate:        "已有同名的通道",
	ChannelHostRequired:         "请填写主机",
	ChannelPortInvalid:          "端口须在 1–65535 之间",
	ChannelUserRequired:         "请填写 SSH 用户名",
	ChannelAuthMethodInvalid:    "认证方式只能是密码或私钥",
	ChannelPasswordRequired:     "请填写密码",
	ChannelPrivateKeyRequired:   "请提供私钥",
	ChannelSOCKS5CredentialPair: "SOCKS5 用户名和密码要么都填，要么都不填",
	ChannelPassphraseMissing:    "私钥已加密，请填写口令",
	ChannelPassphraseWrong:      "私钥口令错误",
	ChannelKeyInvalid:           "无法识别的私钥格式，支持 OpenSSH 与 PEM 格式的 RSA、ECDSA、Ed25519 私钥",
	ChannelViaNotFound:          "经由的通道不存在",
	ChannelViaCycle:             "不能经由自己，也不能经由会形成环路的通道",
	ChannelChainTooLong:         "链路最多 5 跳，当前为 %d 跳",
	ChannelHopFailed:            "第 %d 跳 %s（%s）：%s",
	ChannelHostKeyChanged:       "第 %d 跳 %s（%s）：主机密钥已变化，请先重新确认该通道的主机密钥",
	ChannelInUse:                "通道仍被使用，不能删除：%s",
	ChannelNotSSH:               "只有 SSH 跳板通道有主机密钥",
	ChannelReasonUnreachable:    "无法连接（%s）",
	ChannelReasonTimeout:        "连接超时",
	ChannelReasonCanceled:       "已取消",
	ChannelReasonProtocol:       "协议错误（%s）",
	ChannelReasonNegotiation:    "方法协商失败（%s）",
	ChannelReasonAuthFailed:     "认证失败",
	ChannelReasonHostKeyUnknown: "主机密钥未确认",
	ChannelReasonHostKeyChanged: "主机密钥已变化",

	DataSourceNotFound:           "数据源不存在",
	DataSourceNameInvalid:        "名称须为 1–64 个字符",
	DataSourceNameDuplicate:      "已有同名的数据源",
	DataSourceHostRequired:       "请填写主机",
	DataSourcePortInvalid:        "端口须在 1–65535 之间",
	DataSourceUserRequired:       "请填写用户名",
	DataSourceAuthMethodInvalid:  "认证方式只能是密码或私钥",
	DataSourcePasswordRequired:   "请填写密码",
	DataSourcePrivateKeyRequired: "请提供私钥",
	DataSourcePassphraseMissing:  "私钥已加密，请填写口令",
	DataSourcePassphraseWrong:    "私钥口令错误",
	DataSourceKeyInvalid:         "无法识别的私钥格式，支持 OpenSSH 与 PEM 格式的 RSA、ECDSA、Ed25519 私钥",
	DataSourceTLSPairRequired:    "客户端证书与客户端私钥必须同时提供",
	DataSourceCAInvalid:          "无法解析 CA 证书（需要 PEM 格式）",
	DataSourceClientCertInvalid:  "无法解析客户端证书（需要 PEM 格式）",
	DataSourceClientKeyInvalid:   "无法解析客户端私钥（需要 PEM 格式），或与客户端证书不匹配",
	DataSourceChannelNotFound:    "所选的网络通道不存在",
	DataSourceConfigInvalid:      "数据源设置无效",
	DataSourceTestFailed:         "第 %d 跳 %s（%s）：%s",
	DataSourceNotServerFile:      "只有服务器文件数据源有目标主机密钥",
	DataSourceReasonUnreachable:  "无法连接（%s）",
	DataSourceReasonTimeout:      "连接超时",
	DataSourceReasonCanceled:     "已取消",
	DataSourceReasonAuthFailed:   "认证失败（%s）",
	DataSourceReasonTLS:          "TLS 握手失败（%s）",
	DataSourceReasonCertificate:  "证书校验失败（%s）",
	DataSourceReasonFailed:       "%s",
	DataSourceDatabasesFailed:    "读取数据库列表失败：%s",

	JobNotFound:               "任务不存在",
	JobNameInvalid:            "任务名称须为 1–64 个字符",
	JobNameDuplicate:          "已有同名的任务",
	JobTypeUnsupported:        "本版本只支持备份任务",
	JobDataSourceNotFound:     "所选的数据源不存在",
	JobDataSourceUnsupported:  "本版本只支持 MySQL 与 PostgreSQL 数据源",
	JobDataSourceNotReady:     "数据源状态不是“正常”，请先测试连接",
	JobStorageNotFound:        "所选的存储不存在",
	JobStorageNotReady:        "存储状态不是“正常”，请先测试连接",
	JobScopeInvalid:           "备份范围只能是整个实例或指定数据库",
	JobDatabasesRequired:      "至少选择一个数据库",
	JobMethodUnsupported:      "本版本只支持仅全量",
	JobExcludeInvalid:         "排除表格式不正确：%s（MySQL 写作 库.表，PostgreSQL 写作 库.模式.表）",
	JobPrefixInvalid:          "路径前缀须为 1–128 个字符，只含字母、数字和 ._-/，不以 / 开头或结尾，不含 .. 或连续的 /",
	JobPrefixConflict:         "路径前缀与任务“%s”在同一存储中重复或互为上下级",
	JobCompressionInvalid:     "压缩方式只能是不压缩、gzip 或 zstd",
	JobScheduleInvalid:        "执行计划不正确：%s",
	JobTimezoneInvalid:        "时区不是合法的 IANA 时区名称",
	JobRetentionDaysInvalid:   "保留天数须在 1–365 之间",
	JobRetentionWeeksInvalid:  "保留周数须在 0–520 之间",
	JobRetentionMonthsInvalid: "保留月数须在 0–120 之间",
	JobRetriesInvalid:         "重试次数须在 0–5 之间",
	JobRetryIntervalInvalid:   "重试间隔须在 1–120 分钟之间",
	JobTimeoutInvalid:         "超时时长须在 10 分钟到 48 小时之间",
	JobImmutableField:         "数据源、存储和路径前缀创建后不能修改，需要时请新建任务",
	JobRunActive:              "任务正在运行或排队，请先取消再删除",
	JobSnapshotsNotDeleted:    "任务已删除，但有 %d 份快照未能删除，可以用 kopia 命令行手动处理",
	JobSnapshotsUnreachable:   "任务已删除，但无法打开存储，它的快照未能删除，可以用 kopia 命令行手动处理",
	JobRunAlreadyActive:       "任务已在运行或排队",
	JobRunNotFound:            "运行记录不存在",
	JobRunFinished:            "运行已结束，不能取消",
	JobStatsStorageUnreadable: "无法读取存储中的快照，请检查存储状态",
}
