package code

var zhCN = map[int]string{ //nolint:gosec // 错误文案中的“密码”字样被误判为硬编码凭据
	ServerError:         "服务器内部错误",
	Unauthorized:        "未登录或登录已过期",
	CrossOriginRejected: "跨站请求被拒绝",

	AlreadyInitialized:    "已初始化：管理员账号已存在",
	SetupCodeInvalid:      "设置码不正确",
	UsernameInvalid:       "用户名须为 3–32 个字符，只能包含小写字母、数字以及 . _ -",
	PasswordTooShort:      "密码至少需要 12 个字符",
	LoginFailed:           "用户名或密码错误",
	TooManyAttempts:       "尝试次数过多，请在 %d 分钟后重试",
	CurrentPasswordWrong:  "当前密码不正确",
	NotInitialized:        "尚未创建管理员，请通过网页完成首次设置",
	SessionRequired:       "该操作只能在浏览器登录后进行，API 令牌无权调用",
	PasswordLoginDisabled: "密码登录已关闭",
	ReauthPasswordWrong:   "登录密码不正确",

	TokenInvalid:       "令牌无效",
	TokenRevoked:       "令牌已吊销",
	TokenExpired:       "令牌已过期",
	TokenNameInvalid:   "名称须为 1–64 个字符",
	TokenNameDuplicate: "已有同名的有效令牌",
	TokenExpiryInvalid: "有效期只能是 30 天、90 天、1 年或永不过期",
	TokenNotFound:      "令牌不存在",

	OIDCFieldRequired:              "显示名称、Issuer、Client ID 与 Client Secret 均为必填",
	OIDCRedirectInvalid:            "回调地址无效",
	OIDCIssuerUnreachable:          "无法连接 %s：%s",
	OIDCDiscoveryInvalid:           "OIDC discovery 文档无效或 Issuer 不一致：%s",
	OIDCResetConfirmRequired:       "修改 Issuer 或 Client ID 会清除已有绑定，请确认后再保存",
	OIDCNotConfigured:              "尚未配置 OIDC",
	OIDCAlreadyBound:               "已绑定 OIDC 身份，请先解除当前绑定",
	PasswordLoginDisableNotAllowed: "需要先绑定 OIDC 身份，并用它成功登录一次，才能关闭密码登录",

	StorageNotFound:              "存储不存在",
	StorageNameInvalid:           "名称须为 1–64 个字符",
	StorageNameDuplicate:         "已有同名的存储",
	StoragePathRelative:          "本地目录必须是绝对路径",
	StorageS3FieldRequired:       "Endpoint、Bucket、Access Key 与 Secret Key 均为必填",
	StorageEndpointScheme:        "Endpoint 不含协议，去掉 http:// 或 https://，是否使用 HTTPS 由开关决定",
	StorageLocationInUse:         "该位置已被存储「%s」使用",
	StorageLocationNotEmpty:      "目标位置不为空，且不是 kopia 仓库",
	StorageUnreachable:           "无法连接：%s",
	StorageNotWritable:           "目标位置不可写：%s",
	StorageNotDirectory:          "路径不是目录：%s",
	StorageNoAccess:              "无权访问目标位置：%s",
	StorageBucketNotFound:        "Bucket 不存在",
	StorageAccessDenied:          "Access Denied：Access Key 或 Secret Key 不正确，或没有权限（%s）",
	StorageKeyRequired:           "请提供仓库密钥",
	StorageKeyTooShort:           "密码至少需要 12 个字符",
	StorageKeyNotConfirmed:       "请先确认已保存这把密钥",
	StorageKeyInvalid:            "密钥不正确，无法解开这个仓库",
	StorageManagedKeyInvalid:     "保存的密钥无法打开该位置的仓库，请用“重新解锁”提供正确的密钥",
	StorageNotRepository:         "目标位置不是 kopia 仓库",
	StorageLocationChangeConfirm: "更改存储位置需要确认",
	StorageAlreadyRepository:     "目标位置在测试之后已变成 kopia 仓库，没有覆盖它；请重新测试连接",
	StorageReauthRequired:        "请先验证身份",
	StorageDirNameInvalid:        "文件夹名称不能为空，也不能包含 /",
	StorageDirExists:             "已有同名的文件夹",
	StorageDirNoPermission:       "没有写权限，无法在这里新建文件夹",
	StorageDirNoAccess:           "无权访问这个目录",
	StorageDirCreateFailed:       "新建文件夹失败：%s",
	StorageInUse:                 "存储仍被任务引用，不能删除：%s",
	StorageLocationLocked:        "存储仍被任务引用，不能更改位置：%s",

	ChannelNotFound:             "通道不存在",
	ChannelNameInvalid:          "名称须为 1–64 个字符",
	ChannelNameDuplicate:        "已有同名的通道",
	ChannelHostRequired:         "请填写主机",
	ChannelPortInvalid:          "端口须在 1–65535 之间",
	ChannelUserRequired:         "请填写 SSH 用户名",
	ChannelAuthMethodInvalid:    "认证方式只能是密码或私钥",
	ChannelPasswordRequired:     "请填写密码",
	ChannelPrivateKeyRequired:   "请提供私钥",
	ChannelSOCKS5CredentialPair: "SOCKS5 用户名和密码要么都填，要么都不填",
	ChannelPassphraseMissing:    "私钥已加密，请填写口令",
	ChannelPassphraseWrong:      "私钥口令错误",
	ChannelKeyInvalid:           "无法识别的私钥格式，支持 OpenSSH 与 PEM 格式的 RSA、ECDSA、Ed25519 私钥",
	ChannelViaNotFound:          "经由的通道不存在",
	ChannelViaCycle:             "不能经由自己，也不能经由会形成环路的通道",
	ChannelChainTooLong:         "链路最多 5 跳，当前为 %d 跳",
	ChannelHopFailed:            "第 %d 跳 %s（%s）：%s",
	ChannelHostKeyChanged:       "第 %d 跳 %s（%s）：主机密钥已变化，请先重新确认该通道的主机密钥",
	ChannelInUse:                "通道仍被使用，不能删除：%s",
	ChannelNotSSH:               "只有 SSH 跳板通道有主机密钥",
	ChannelReasonUnreachable:    "无法连接（%s）",
	ChannelReasonTimeout:        "连接超时",
	ChannelReasonCanceled:       "已取消",
	ChannelReasonProtocol:       "协议错误（%s）",
	ChannelReasonNegotiation:    "方法协商失败（%s）",
	ChannelReasonAuthFailed:     "认证失败",
	ChannelReasonHostKeyUnknown: "主机密钥未确认",
	ChannelReasonHostKeyChanged: "主机密钥已变化",

	DataSourceNotFound:           "数据源不存在",
	DataSourceNameInvalid:        "名称须为 1–64 个字符",
	DataSourceNameDuplicate:      "已有同名的数据源",
	DataSourceHostRequired:       "请填写主机",
	DataSourcePortInvalid:        "端口须在 1–65535 之间",
	DataSourceUserRequired:       "请填写用户名",
	DataSourceAuthMethodInvalid:  "认证方式只能是密码或私钥",
	DataSourcePasswordRequired:   "请填写密码",
	DataSourcePrivateKeyRequired: "请提供私钥",
	DataSourcePassphraseMissing:  "私钥已加密，请填写口令",
	DataSourcePassphraseWrong:    "私钥口令错误",
	DataSourceKeyInvalid:         "无法识别的私钥格式，支持 OpenSSH 与 PEM 格式的 RSA、ECDSA、Ed25519 私钥",
	DataSourceTLSPairRequired:    "客户端证书与客户端私钥必须同时提供",
	DataSourceCAInvalid:          "无法解析 CA 证书（需要 PEM 格式）",
	DataSourceClientCertInvalid:  "无法解析客户端证书（需要 PEM 格式）",
	DataSourceClientKeyInvalid:   "无法解析客户端私钥（需要 PEM 格式），或与客户端证书不匹配",
	DataSourceChannelNotFound:    "所选的网络通道不存在",
	DataSourceConfigInvalid:      "数据源设置无效",
	DataSourceTestFailed:         "第 %d 跳 %s（%s）：%s",
	DataSourceNotServerFile:      "只有服务器文件数据源有目标主机密钥",
	DataSourceReasonUnreachable:  "无法连接（%s）",
	DataSourceReasonTimeout:      "连接超时",
	DataSourceReasonCanceled:     "已取消",
	DataSourceReasonAuthFailed:   "认证失败（%s）",
	DataSourceReasonTLS:          "TLS 握手失败（%s）",
	DataSourceReasonCertificate:  "证书校验失败（%s）",
	DataSourceReasonFailed:       "%s",
	DataSourceDatabasesFailed:    "读取数据库列表失败：%s",
	DataSourceInUse:              "数据源仍被任务引用，不能删除：%s",

	JobNotFound:               "任务不存在",
	JobNameInvalid:            "任务名称须为 1–64 个字符",
	JobNameDuplicate:          "已有同名的任务",
	JobTypeUnsupported:        "本版本只支持备份任务",
	JobDataSourceNotFound:     "所选的数据源不存在",
	JobDataSourceUnsupported:  "本版本只支持 MySQL 与 PostgreSQL 数据源",
	JobDataSourceNotReady:     "数据源状态不是“正常”，请先测试连接",
	JobStorageNotFound:        "所选的存储不存在",
	JobStorageNotReady:        "存储状态不是“正常”，请先测试连接",
	JobScopeInvalid:           "备份范围只能是整个实例或指定数据库",
	JobDatabasesRequired:      "至少选择一个数据库",
	JobMethodUnsupported:      "本版本只支持仅全量",
	JobExcludeInvalid:         "排除表格式不正确：%s（MySQL 写作 库.表，PostgreSQL 写作 库.模式.表）",
	JobPrefixInvalid:          "路径前缀须为 1–128 个字符，只含字母、数字和 ._-/，不以 / 开头或结尾，不含 .. 或连续的 /",
	JobPrefixConflict:         "路径前缀与任务“%s”在同一存储中重复或互为上下级",
	JobCompressionInvalid:     "压缩方式只能是不压缩、gzip 或 zstd",
	JobScheduleInvalid:        "执行计划不正确：%[1]s", // 参数依次为中文、英文原因
	JobTimezoneInvalid:        "时区不是合法的 IANA 时区名称",
	JobRetentionDaysInvalid:   "保留天数须在 1–365 之间",
	JobRetentionWeeksInvalid:  "保留周数须在 0–520 之间",
	JobRetentionMonthsInvalid: "保留月数须在 0–120 之间",
	JobRetriesInvalid:         "重试次数须在 0–5 之间",
	JobRetryIntervalInvalid:   "重试间隔须在 1–120 分钟之间",
	JobTimeoutInvalid:         "超时时长须在 10 分钟到 48 小时之间",
	JobImmutableField:         "数据源、存储和路径前缀创建后不能修改，需要时请新建任务",
	JobRunActive:              "任务正在运行或排队，请先取消再删除",
	JobSnapshotsNotDeleted:    "任务已删除，但有 %d 份快照未能删除，可以用 kopia 命令行手动处理",
	JobSnapshotsUnreachable:   "任务已删除，但无法打开存储，它的快照未能删除，可以用 kopia 命令行手动处理",
	JobRunAlreadyActive:       "任务已在运行或排队",
	JobRunNotFound:            "运行记录不存在",
	JobRunFinished:            "运行已结束，不能取消",
	JobStatsStorageUnreadable: "无法读取存储中的快照，请检查存储状态",
	JobReasonStillRunning:     "上一次仍在运行",
	JobReasonRetryVoided:      "下一次计划时间已到，重试作废",
	JobReasonInterrupted:      "OpsNap 重启，运行中断",
	JobReasonRestart:          "OpsNap 重启",
	JobReasonTimeout:          "超时（超过 %s）",
	JobDurationMinutes:        "%d 分钟",
	JobDurationHours:          "%d 小时",
	JobDurationHoursMinutes:   "%d 小时 %d 分钟",

	Language:                    "zh-cn",
	ListSep:                     "、",
	WrapColon:                   "%s: %s",
	WrapFullColon:               "%s：%s",
	RunLogPrepare:               "检查存储、数据源与导出工具",
	RunStorageMissing:           "存储不存在",
	RunStorageNotOK:             "存储“%s”的状态不是“正常”（%s），请先测试存储连接",
	RunDataSourceMissing:        "数据源不存在",
	RunHostKeyChanged:           "数据源“%s”链路上的主机密钥已变化，请先在数据源页面确认新的主机密钥",
	RunLogToolPath:              "导出工具 %s：%s",
	RunOpenStorageFailed:        "打开存储“%s”失败: %s",
	RunLogStorageOpened:         "已打开存储“%s”",
	RunLogConnecting:            "沿网络通道连接数据源“%s”（%s:%d）",
	RunConnectFailed:            "连接数据源失败: %s",
	RunLogConnected:             "已连接，服务端版本 %s",
	RunListDatabasesFailed:      "列出实例中的库失败: %s",
	RunNoDatabases:              "实例中没有可导出的库",
	RunMissingDatabases:         "指定的库在数据源中不存在（或不允许连接）：%s",
	RunLogDatabases:             "导出的库：%s",
	RunStartDumpFailed:          "准备导出失败: %s",
	RunLogForwarding:            "已在本机 127.0.0.1 开临时端口，导出工具的连接经链路转发到数据源",
	RunLogExporting:             "导出并流式写入仓库，路径前缀 %s，压缩 %s",
	RunLogExportChecked:         "导出工具均正常退出，导出内容通过完整性检查",
	RunLogFileSize:              "%s：%d 字节",
	RunLogSnapshotVerified:      "快照 %s 已写入并读回校验：%d 个文件，共 %d 字节，新增上传 %d 字节",
	RunLogListSnapshotsFailed:   "读取本任务的快照失败，本次不应用保留策略: %s",
	RunLogRetention:             "保留策略：最近 %d 天、%d 周、%d 个月；本任务共 %d 份快照，保留 %d 份，删除 %d 份",
	RunLogDeleteFailed:          "删除过期快照失败（本次运行仍为成功）: %s",
	RunLogDeleted:               "已删除 %d 份过期快照，开始快速维护",
	RunLogMaintainFailed:        "快速维护失败（本次运行仍为成功）: %s",
	RunLogMaintained:            "快速维护完成；删除的数据在之后的完整维护中释放",
	RunLogCanceled:              "运行已取消：已终止导出工具、关闭端口转发并删除临时文件，未形成快照",
	RunLogAborted:               "%s：已终止导出工具，未形成快照",
	RunReasonEllipsis:           "……",
	DumpErrInvalidOptions:       "导出选项无效",
	DumpErrToolNotFound:         "找不到导出工具",
	DumpErrToolVersion:          "导出工具版本过低",
	DumpErrUnsupportedTLS:       "导出工具无法按数据源的 TLS 设置连接",
	DumpErrPrivilege:            "数据源账号缺少权限",
	DumpErrIncomplete:           "导出内容不完整",
	DumpErrClosed:               "导出已终止",
	DumpToolFailed:              "%s 失败（退出码 %d）",
	DumpStderrOmitted:           "（省略了前面 %d 字节的错误输出）",
	DumpViaChannelFailed:        "；经链路连接数据源失败: %s",
	DumpUnsupportedType:         "%s：不支持导出 %q 类型的数据源",
	DumpNoDialer:                "%s：缺少网络链路",
	DumpNoDatabases:             "%s：至少选择一个库",
	DumpEmptyDatabase:           "%s：库名为空",
	DumpGlobalsPGOnly:           "%s：全局对象只适用于 PostgreSQL",
	DumpMySQLOnlyOptions:        "%s：账号与权限、存储过程、触发器、事件只适用于 MySQL",
	DumpExcludeFormat:           "%s：排除规则 %q 应写作 %s",
	DumpExcludeFormatMySQL:      "库.表",
	DumpExcludeFormatPG:         "库.模式.表",
	DumpToolMissing:             "%s：%s（先在 PATH 中查找，再在配置项 tools.dir 指定的目录中查找）。修复：在主控端安装 %s，或把 %s 放进 tools.dir",
	DumpPkgMySQL:                "MySQL 客户端",
	DumpPkgPostgreSQL:           "PostgreSQL 客户端",
	DumpToolVersionUnknown:      "无法确定 %s（%s）的版本: %s",
	DumpConnect:                 "连接数据源: %s",
	DumpNoSystemCA:              "%s：找不到系统 CA 证书包，导出工具无法校验服务端证书。修复：在数据源的 TLS 设置中提供 CA 证书",
	DumpStartTool:               "启动 %s: %s",
	DumpReadOutput:              "读取 %s 的输出: %s",
	DumpGlobalsSuperuser:        "%s：导出全局对象需要超级用户权限（pg_dumpall 读取 pg_authid）: %s",
	DumpIncompleteMySQL:         "%s：mysqldump 的输出没有以完成标记（-- Dump completed）结尾",
	DumpIncompletePGArchive:     "%s：pg_dump 的输出不是完整的 custom 格式归档头",
	DumpIncompletePGGlobals:     "%s：pg_dumpall 的输出没有完成标记（PostgreSQL database cluster dump complete）",
	DumpMariaDBTLS:              "%s：主控端的 mysqldump 来自 MariaDB（%s），在服务端不支持 TLS 时会退回明文，且只能连同主机名一起校验证书，无法保证数据源的 TLS 模式 %q。修复：在 PATH 或 tools.dir 中提供 MySQL 官方的 mysqldump",
	DumpMySQLDumpOlder:          "mysqldump 版本 %d.%d 低于服务端 %d.%d，照常导出；如果导出失败，请在 PATH 或 tools.dir 中提供不低于服务端版本的 mysqldump",
	DumpVerifyCAOnly:            "mysqldump 经本机端口转发连接数据源，无法按主机名校验服务端证书，本次只校验 CA；主机名已在 OpsNap 经同一链路连接数据源时校验",
	DumpListTables:              "列出要导出的表: %s",
	DumpNonInnoDB:               "以下 %d 张表不是 InnoDB，导出时不保证与其他表一致：%s",
	DumpExcludeUnmatched:        "排除规则 %s 未匹配任何表",
	DumpAccounts:                "导出账号与权限: %s",
	DumpAccountsPrivilege:       "%s：导出账号与权限需要读取 mysql 系统库（%s）。修复：GRANT SELECT ON mysql.* TO '%s'@'%s';",
	DumpPGToolTooOld:            "%s：%s 大版本 %d 低于服务端 %d。修复：在主控端安装 PostgreSQL %d 或更新版本的客户端，放在 PATH 或 tools.dir 中",
	DumpPGPasswordNewline:       "%s：密码含换行符，无法写入 pg_dump 的密码文件",
	DumpCheckExclude:            "检查排除规则 %s: %s",
	KopiaErrInvalidSnapshot:     "快照请求不合法",
	KopiaErrVerify:              "读回校验快照",
	KopiaErrNotJobSnapshot:      "快照不存在或不属于该任务",
	KopiaUnsupportedCompression: "%s: 不支持的压缩方式 %q",
	KopiaNoPrefix:               "%s: 缺少路径前缀",
	KopiaNoFiles:                "%s: 没有文件",
	KopiaBadFileName:            "%s: 文件名 %q 不合法",
	KopiaDupFileName:            "%s: 文件名 %q 重复",
	KopiaNoReader:               "%s: 文件 %q 没有内容",
	KopiaWriteSnapshot:          "写入快照: %s",
	KopiaWriteIncomplete:        "写入快照未完成: %s",
	KopiaWriteFatal:             "写入快照失败: %d 个文件出错",
	KopiaSaveManifest:           "保存快照清单: %s",
	KopiaVerifyDeleteFailed:     "%s: %s（删除清单也失败: %s）",
	KopiaRootNotDir:             "快照根不是目录",
	KopiaReadDir:                "读取快照目录: %s",
	KopiaFileCount:              "快照中有 %d 个文件，应为 %d 个",
	KopiaFileMissing:            "快照中缺少文件 %s",
	KopiaFileSize:               "文件 %s 大小为 %d，应为 %d",
	KopiaFileNoObject:           "文件 %s 没有内容标识",
	KopiaFileIncomplete:         "文件 %s 内容不完整: %s",
	KopiaListSnapshots:          "读取快照列表: %s",
	KopiaLoadManifests:          "读取快照清单: %s",
	KopiaDeleteSnapshots:        "删除快照: %s",
	KopiaMaintainMode:           "不支持的维护方式 %q",
	KopiaMaintainUnsupported:    "仓库连接不支持维护",
	KopiaMaintain:               "仓库维护（%s）: %s",
	NetErrTooManyHops:           "链路超过 5 跳",
	NetErrCycle:                 "链路成环",
	NetErrInvalidHop:            "通道配置不完整",
	NetErrAuthFailed:            "认证失败",
	NetErrNegotiation:           "SOCKS5 方法协商失败",
	NetErrProtocol:              "协议错误",
	NetErrHostKeyUnknown:        "主机密钥未确认",
	NetErrHostKeyChanged:        "主机密钥已变化",
	NetErrPassphraseMissing:     "私钥已加密，缺少口令",
	NetErrPassphraseWrong:       "私钥口令错误",
	NetErrKeyInvalid:            "无法识别的私钥格式",
	NetHopFailed:                "第 %d 跳 %s（%s）：%s",
	NetHostKeyChangedDetail:     "%s：保存的是 %s，现在出示的是 %s %s",
	NetHostKeyUnknownDetail:     "%s：%s %s",
	NetTimeout:                  "连接超时: %s",
	NetCanceled:                 "已取消: %s",
	NetSSHHandshake:             "%s：SSH 握手失败: %s",
	NetSocksNetwork:             "SOCKS5 不支持 %s",
	NetSocksClosed:              "%s：代理断开了连接",
	NetSocksNotSocks:            "%s：对端不是 SOCKS5 代理",
	NetSocksAuthRequired:        "%s：代理要求认证",
	NetSocksNoUserPass:          "%s：代理不接受用户名密码认证",
	NetSocksBadMethod:           "%s：代理选择了未提供的认证方式 %d",
	NetSocksCredTooLong:         "%s：用户名或密码超过 255 字节",
	NetSocksReply1:              "代理内部错误",
	NetSocksReply2:              "代理规则不允许",
	NetSocksReply3:              "网络不可达",
	NetSocksReply4:              "主机不可达",
	NetSocksReply5:              "连接被拒绝",
	NetSocksReply6:              "TTL 过期",
	NetSocksReply7:              "代理不支持 CONNECT",
	NetSocksReply8:              "代理不支持该地址类型",
	NetSocksReplyCode:           "错误码 %d",
	NetSocksBadPort:             "无效的端口 %q",
	NetSocksHostTooLong:         "主机名超过 255 字节",
	NetSocksBadReply:            "%s：CONNECT 应答无效",
	NetSocksConnectFailed:       "SOCKS5 代理无法连接 %s：%s",
	NetSocksBadAddrType:         "%s：CONNECT 应答地址类型无效",
	NetUnknownKind:              "%s：未知的类型 %q",
	NetNoHost:                   "%s：缺少主机",
	NetBadPort:                  "%s：端口 %d 超出 1–65535",
	NetNoSSHUser:                "%s：缺少 SSH 用户名",
	NetSSHAuthRequired:          "%s：SSH 认证需要密码或私钥之一",
	NetHopCount:                 "%s：当前 %d 跳",
	NetChannelTwice:             "%s：通道 %s 出现了两次",
	NetHopInvalid:               "第 %d 跳 %s：%s",
	NetDialFailed:               "连接 %s 失败: %s",
	NetNotSSHTarget:             "%s：目标不是 SSH 主机",
	ConnErrInvalidConfig:        "数据源配置无效",
	ConnNoUser:                  "%s：缺少用户名",
	ConnUnknownTLSMode:          "%s：未知的 TLS 模式",
	ConnCANotPEM:                "无法解析 CA 证书（需要 PEM 格式）",
	ConnCertNotPEM:              "无法解析客户端证书（需要 PEM 格式）",
	ConnKeyInvalid:              "无法解析客户端私钥（需要 PEM 格式）",
	ConnKeyMismatch:             "客户端私钥与证书不匹配",
	ConnCertMissing:             "提供了客户端私钥，还需要客户端证书",
	ConnKeyMissing:              "提供了客户端证书，还需要客户端私钥",
	ConnNoPeerCert:              "服务端没有出示证书",
	WrapParen:                   "%s（%s）",
	KopiaErrInvalidPassword:     "密钥不正确，无法解开这个仓库",
	KopiaErrNotEmpty:            "目标位置不为空，且不是 kopia 仓库",
	KopiaErrAlreadyRepository:   "目标位置已是 kopia 仓库",
	KopiaErrNotRepository:       "目标位置不是 kopia 仓库",
	KopiaCreate:                 "创建 kopia 仓库: %s",
	KopiaConnect:                "连接 kopia 仓库: %s",
	KopiaNotDirectory:           "%s 不是目录",
	KopiaErrRelativePath:        "本地目录必须是绝对路径",
	KopiaErrEndpointScheme:      "endpoint 不含协议（去掉 http:// 或 https://）",
	KopiaErrUnknownKind:         "未知的存储类型",
	KopiaGenerateKey:            "生成仓库密钥: %s",
	KopiaErrInvalidDirName:      "文件夹名称不能为空，也不能包含 /",
	KopiaReadSnapshot:           "读取快照 %s: %s",
	KopiaUsage:                  "统计快照占用: %s",
	StorageErrNotReady:          "存储状态不是正常",
	SecretErrInvalidKey:         "主密钥格式不正确：需要 base64 编码的 32 字节随机数",
	SecretErrDecrypt:            "解密失败：密文损坏或主密钥不匹配",
	SecretGenerateKey:           "生成主密钥: %s",
	SecretInitCipher:            "初始化加密: %s",
	SecretRandom:                "生成随机数: %s",
	SecretErrKeyMissing:         "主密钥缺失",
	SecretErrKeyMismatch:        "主密钥与数据库不匹配",
	SecretErrNotInitialized:     "主密钥尚未初始化",
	ProbeVersionUnrecognized:    "无法从 %q 中识别版本号",
	DataSourceListUnsupported:   "不支持读取数据库列表的数据源类型 %q",
}
