// Code generated by MockGen. DO NOT EDIT.
// Source: job.go
//
// Generated by this command:
//
//	mockgen -source job.go -destination mock/job.go
//

// Package mock_job_repo is a generated GoMock package.
package mock_job_repo

import (
	context "context"
	reflect "reflect"

	job_entity "github.com/opskat/opsnap/internal/model/entity/job_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockJobRepo is a mock of JobRepo interface.
type MockJobRepo struct {
	ctrl     *gomock.Controller
	recorder *MockJobRepoMockRecorder
	isgomock struct{}
}

// MockJobRepoMockRecorder is the mock recorder for MockJobRepo.
type MockJobRepoMockRecorder struct {
	mock *MockJobRepo
}

// NewMockJobRepo creates a new mock instance.
func NewMockJobRepo(ctrl *gomock.Controller) *MockJobRepo {
	mock := &MockJobRepo{ctrl: ctrl}
	mock.recorder = &MockJobRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJobRepo) EXPECT() *MockJobRepoMockRecorder {
	return m.recorder
}

// ClearRunNow mocks base method.
func (m *MockJobRepo) ClearRunNow(ctx context.Context, id int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ClearRunNow", ctx, id)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ClearRunNow indicates an expected call of ClearRunNow.
func (mr *MockJobRepoMockRecorder) ClearRunNow(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ClearRunNow", reflect.TypeOf((*MockJobRepo)(nil).ClearRunNow), ctx, id)
}

// Create mocks base method.
func (m *MockJobRepo) Create(ctx context.Context, j *job_entity.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockJobRepoMockRecorder) Create(ctx, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockJobRepo)(nil).Create), ctx, j)
}

// Delete mocks base method.
func (m *MockJobRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockJobRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockJobRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockJobRepo) Find(ctx context.Context, id int64) (*job_entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*job_entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockJobRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockJobRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockJobRepo) FindByName(ctx context.Context, name string) (*job_entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*job_entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockJobRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockJobRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockJobRepo) List(ctx context.Context) ([]*job_entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*job_entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockJobRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockJobRepo)(nil).List), ctx)
}

// ListByDataSource mocks base method.
func (m *MockJobRepo) ListByDataSource(ctx context.Context, dataSourceID int64) ([]*job_entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDataSource", ctx, dataSourceID)
	ret0, _ := ret[0].([]*job_entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDataSource indicates an expected call of ListByDataSource.
func (mr *MockJobRepoMockRecorder) ListByDataSource(ctx, dataSourceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDataSource", reflect.TypeOf((*MockJobRepo)(nil).ListByDataSource), ctx, dataSourceID)
}

// ListByStorage mocks base method.
func (m *MockJobRepo) ListByStorage(ctx context.Context, storageID int64) ([]*job_entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByStorage", ctx, storageID)
	ret0, _ := ret[0].([]*job_entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByStorage indicates an expected call of ListByStorage.
func (mr *MockJobRepoMockRecorder) ListByStorage(ctx, storageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByStorage", reflect.TypeOf((*MockJobRepo)(nil).ListByStorage), ctx, storageID)
}

// ListRunNow mocks base method.
func (m *MockJobRepo) ListRunNow(ctx context.Context) ([]*job_entity.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRunNow", ctx)
	ret0, _ := ret[0].([]*job_entity.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRunNow indicates an expected call of ListRunNow.
func (mr *MockJobRepoMockRecorder) ListRunNow(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRunNow", reflect.TypeOf((*MockJobRepo)(nil).ListRunNow), ctx)
}

// Save mocks base method.
func (m *MockJobRepo) Save(ctx context.Context, j *job_entity.Job) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, j)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockJobRepoMockRecorder) Save(ctx, j any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockJobRepo)(nil).Save), ctx, j)
}

// SetSnapshotCount mocks base method.
func (m *MockJobRepo) SetSnapshotCount(ctx context.Context, id int64, n int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetSnapshotCount", ctx, id, n)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetSnapshotCount indicates an expected call of SetSnapshotCount.
func (mr *MockJobRepoMockRecorder) SetSnapshotCount(ctx, id, n any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetSnapshotCount", reflect.TypeOf((*MockJobRepo)(nil).SetSnapshotCount), ctx, id, n)
}
