// Code generated by MockGen. DO NOT EDIT.
// Source: run.go
//
// Generated by this command:
//
//	mockgen -source run.go -destination mock/run.go
//

// Package mock_job_repo is a generated GoMock package.
package mock_job_repo

import (
	context "context"
	reflect "reflect"

	job_entity "github.com/opskat/opsnap/internal/model/entity/job_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockRunRepo is a mock of RunRepo interface.
type MockRunRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRunRepoMockRecorder
	isgomock struct{}
}

// MockRunRepoMockRecorder is the mock recorder for MockRunRepo.
type MockRunRepoMockRecorder struct {
	mock *MockRunRepo
}

// NewMockRunRepo creates a new mock instance.
func NewMockRunRepo(ctrl *gomock.Controller) *MockRunRepo {
	mock := &MockRunRepo{ctrl: ctrl}
	mock.recorder = &MockRunRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRunRepo) EXPECT() *MockRunRepoMockRecorder {
	return m.recorder
}

// Active mocks base method.
func (m *MockRunRepo) Active(ctx context.Context, jobID int64) (*job_entity.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Active", ctx, jobID)
	ret0, _ := ret[0].(*job_entity.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Active indicates an expected call of Active.
func (mr *MockRunRepoMockRecorder) Active(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Active", reflect.TypeOf((*MockRunRepo)(nil).Active), ctx, jobID)
}

// Create mocks base method.
func (m *MockRunRepo) Create(ctx context.Context, r *job_entity.Run) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, r)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockRunRepoMockRecorder) Create(ctx, r any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRunRepo)(nil).Create), ctx, r)
}

// DeleteByJob mocks base method.
func (m *MockRunRepo) DeleteByJob(ctx context.Context, jobID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByJob", ctx, jobID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByJob indicates an expected call of DeleteByJob.
func (mr *MockRunRepoMockRecorder) DeleteByJob(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByJob", reflect.TypeOf((*MockRunRepo)(nil).DeleteByJob), ctx, jobID)
}

// Find mocks base method.
func (m *MockRunRepo) Find(ctx context.Context, id int64) (*job_entity.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*job_entity.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockRunRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRunRepo)(nil).Find), ctx, id)
}

// HasScheduled mocks base method.
func (m *MockRunRepo) HasScheduled(ctx context.Context, jobID, scheduledAt int64) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasScheduled", ctx, jobID, scheduledAt)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasScheduled indicates an expected call of HasScheduled.
func (mr *MockRunRepoMockRecorder) HasScheduled(ctx, jobID, scheduledAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasScheduled", reflect.TypeOf((*MockRunRepo)(nil).HasScheduled), ctx, jobID, scheduledAt)
}

// LastSuccess mocks base method.
func (m *MockRunRepo) LastSuccess(ctx context.Context, jobID int64) (*job_entity.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LastSuccess", ctx, jobID)
	ret0, _ := ret[0].(*job_entity.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// LastSuccess indicates an expected call of LastSuccess.
func (mr *MockRunRepoMockRecorder) LastSuccess(ctx, jobID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LastSuccess", reflect.TypeOf((*MockRunRepo)(nil).LastSuccess), ctx, jobID)
}

// Latest mocks base method.
func (m *MockRunRepo) Latest(ctx context.Context) (map[int64]*job_entity.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Latest", ctx)
	ret0, _ := ret[0].(map[int64]*job_entity.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Latest indicates an expected call of Latest.
func (mr *MockRunRepoMockRecorder) Latest(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Latest", reflect.TypeOf((*MockRunRepo)(nil).Latest), ctx)
}

// ListActive mocks base method.
func (m *MockRunRepo) ListActive(ctx context.Context) ([]*job_entity.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListActive", ctx)
	ret0, _ := ret[0].([]*job_entity.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListActive indicates an expected call of ListActive.
func (mr *MockRunRepoMockRecorder) ListActive(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListActive", reflect.TypeOf((*MockRunRepo)(nil).ListActive), ctx)
}

// Page mocks base method.
func (m *MockRunRepo) Page(ctx context.Context, jobID int64, offset, limit int) ([]*job_entity.Run, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Page", ctx, jobID, offset, limit)
	ret0, _ := ret[0].([]*job_entity.Run)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Page indicates an expected call of Page.
func (mr *MockRunRepoMockRecorder) Page(ctx, jobID, offset, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Page", reflect.TypeOf((*MockRunRepo)(nil).Page), ctx, jobID, offset, limit)
}

// RecentFinished mocks base method.
func (m *MockRunRepo) RecentFinished(ctx context.Context, jobID int64, limit int) ([]*job_entity.Run, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecentFinished", ctx, jobID, limit)
	ret0, _ := ret[0].([]*job_entity.Run)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecentFinished indicates an expected call of RecentFinished.
func (mr *MockRunRepoMockRecorder) RecentFinished(ctx, jobID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecentFinished", reflect.TypeOf((*MockRunRepo)(nil).RecentFinished), ctx, jobID, limit)
}

// SaveIf mocks base method.
func (m *MockRunRepo) SaveIf(ctx context.Context, r *job_entity.Run, from string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveIf", ctx, r, from)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SaveIf indicates an expected call of SaveIf.
func (mr *MockRunRepoMockRecorder) SaveIf(ctx, r, from any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveIf", reflect.TypeOf((*MockRunRepo)(nil).SaveIf), ctx, r, from)
}

// Trim mocks base method.
func (m *MockRunRepo) Trim(ctx context.Context, jobID int64, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Trim", ctx, jobID, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// Trim indicates an expected call of Trim.
func (mr *MockRunRepoMockRecorder) Trim(ctx, jobID, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trim", reflect.TypeOf((*MockRunRepo)(nil).Trim), ctx, jobID, keep)
}
