// Code generated by MockGen. DO NOT EDIT.
// Source: datasource.go
//
// Generated by this command:
//
//	mockgen -source datasource.go -destination mock/datasource.go
//

// Package mock_datasource_repo is a generated GoMock package.
package mock_datasource_repo

import (
	context "context"
	reflect "reflect"

	datasource_entity "github.com/opskat/opsnap/internal/model/entity/datasource_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockDataSourceRepo is a mock of DataSourceRepo interface.
type MockDataSourceRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDataSourceRepoMockRecorder
	isgomock struct{}
}

// MockDataSourceRepoMockRecorder is the mock recorder for MockDataSourceRepo.
type MockDataSourceRepoMockRecorder struct {
	mock *MockDataSourceRepo
}

// NewMockDataSourceRepo creates a new mock instance.
func NewMockDataSourceRepo(ctrl *gomock.Controller) *MockDataSourceRepo {
	mock := &MockDataSourceRepo{ctrl: ctrl}
	mock.recorder = &MockDataSourceRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDataSourceRepo) EXPECT() *MockDataSourceRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockDataSourceRepo) Create(ctx context.Context, d *datasource_entity.DataSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockDataSourceRepoMockRecorder) Create(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockDataSourceRepo)(nil).Create), ctx, d)
}

// Delete mocks base method.
func (m *MockDataSourceRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockDataSourceRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockDataSourceRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockDataSourceRepo) Find(ctx context.Context, id int64) (*datasource_entity.DataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*datasource_entity.DataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockDataSourceRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockDataSourceRepo)(nil).Find), ctx, id)
}

// FindByName mocks base method.
func (m *MockDataSourceRepo) FindByName(ctx context.Context, name string) (*datasource_entity.DataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*datasource_entity.DataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockDataSourceRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockDataSourceRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockDataSourceRepo) List(ctx context.Context) ([]*datasource_entity.DataSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*datasource_entity.DataSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockDataSourceRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockDataSourceRepo)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockDataSourceRepo) Save(ctx context.Context, d *datasource_entity.DataSource) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockDataSourceRepoMockRecorder) Save(ctx, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockDataSourceRepo)(nil).Save), ctx, d)
}
