// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go
//
// Generated by this command:
//
//	mockgen -source storage.go -destination mock/storage.go
//

// Package mock_storage_repo is a generated GoMock package.
package mock_storage_repo

import (
	context "context"
	reflect "reflect"

	storage_entity "github.com/opskat/opsnap/internal/model/entity/storage_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockStorageRepo is a mock of StorageRepo interface.
type MockStorageRepo struct {
	ctrl     *gomock.Controller
	recorder *MockStorageRepoMockRecorder
	isgomock struct{}
}

// MockStorageRepoMockRecorder is the mock recorder for MockStorageRepo.
type MockStorageRepoMockRecorder struct {
	mock *MockStorageRepo
}

// NewMockStorageRepo creates a new mock instance.
func NewMockStorageRepo(ctrl *gomock.Controller) *MockStorageRepo {
	mock := &MockStorageRepo{ctrl: ctrl}
	mock.recorder = &MockStorageRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageRepo) EXPECT() *MockStorageRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockStorageRepo) Create(ctx context.Context, s *storage_entity.Storage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockStorageRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockStorageRepo)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockStorageRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockStorageRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockStorageRepo)(nil).Delete), ctx, id)
}

// Find mocks base method.
func (m *MockStorageRepo) Find(ctx context.Context, id int64) (*storage_entity.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*storage_entity.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockStorageRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockStorageRepo)(nil).Find), ctx, id)
}

// FindByLocationKey mocks base method.
func (m *MockStorageRepo) FindByLocationKey(ctx context.Context, key string) (*storage_entity.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByLocationKey", ctx, key)
	ret0, _ := ret[0].(*storage_entity.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByLocationKey indicates an expected call of FindByLocationKey.
func (mr *MockStorageRepoMockRecorder) FindByLocationKey(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByLocationKey", reflect.TypeOf((*MockStorageRepo)(nil).FindByLocationKey), ctx, key)
}

// FindByName mocks base method.
func (m *MockStorageRepo) FindByName(ctx context.Context, name string) (*storage_entity.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].(*storage_entity.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockStorageRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockStorageRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockStorageRepo) List(ctx context.Context) ([]*storage_entity.Storage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*storage_entity.Storage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockStorageRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockStorageRepo)(nil).List), ctx)
}

// Save mocks base method.
func (m *MockStorageRepo) Save(ctx context.Context, s *storage_entity.Storage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockStorageRepoMockRecorder) Save(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockStorageRepo)(nil).Save), ctx, s)
}
