// Code generated by MockGen. DO NOT EDIT.
// Source: session.go
//
// Generated by this command:
//
//	mockgen -source session.go -destination mock/session.go
//

// Package mock_session_repo is a generated GoMock package.
package mock_session_repo

import (
	context "context"
	reflect "reflect"

	admin_entity "github.com/opskat/opsnap/internal/model/entity/admin_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockSessionRepo is a mock of SessionRepo interface.
type MockSessionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSessionRepoMockRecorder
	isgomock struct{}
}

// MockSessionRepoMockRecorder is the mock recorder for MockSessionRepo.
type MockSessionRepoMockRecorder struct {
	mock *MockSessionRepo
}

// NewMockSessionRepo creates a new mock instance.
func NewMockSessionRepo(ctrl *gomock.Controller) *MockSessionRepo {
	mock := &MockSessionRepo{ctrl: ctrl}
	mock.recorder = &MockSessionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSessionRepo) EXPECT() *MockSessionRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSessionRepo) Create(ctx context.Context, s *admin_entity.Session) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSessionRepoMockRecorder) Create(ctx, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSessionRepo)(nil).Create), ctx, s)
}

// Delete mocks base method.
func (m *MockSessionRepo) Delete(ctx context.Context, id int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSessionRepoMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSessionRepo)(nil).Delete), ctx, id)
}

// DeleteAllExcept mocks base method.
func (m *MockSessionRepo) DeleteAllExcept(ctx context.Context, adminID, keepID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteAllExcept", ctx, adminID, keepID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteAllExcept indicates an expected call of DeleteAllExcept.
func (mr *MockSessionRepoMockRecorder) DeleteAllExcept(ctx, adminID, keepID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteAllExcept", reflect.TypeOf((*MockSessionRepo)(nil).DeleteAllExcept), ctx, adminID, keepID)
}

// Find mocks base method.
func (m *MockSessionRepo) Find(ctx context.Context, id int64) (*admin_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*admin_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockSessionRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockSessionRepo)(nil).Find), ctx, id)
}

// FindByTokenHash mocks base method.
func (m *MockSessionRepo) FindByTokenHash(ctx context.Context, hash string) (*admin_entity.Session, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTokenHash", ctx, hash)
	ret0, _ := ret[0].(*admin_entity.Session)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTokenHash indicates an expected call of FindByTokenHash.
func (mr *MockSessionRepoMockRecorder) FindByTokenHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTokenHash", reflect.TypeOf((*MockSessionRepo)(nil).FindByTokenHash), ctx, hash)
}

// Touch mocks base method.
func (m *MockSessionRepo) Touch(ctx context.Context, id, expiretime, now int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Touch", ctx, id, expiretime, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Touch indicates an expected call of Touch.
func (mr *MockSessionRepoMockRecorder) Touch(ctx, id, expiretime, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Touch", reflect.TypeOf((*MockSessionRepo)(nil).Touch), ctx, id, expiretime, now)
}
