// Code generated by MockGen. DO NOT EDIT.
// Source: setting.go
//
// Generated by this command:
//
//	mockgen -source setting.go -destination mock/setting.go
//

// Package mock_setting_repo is a generated GoMock package.
package mock_setting_repo

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSettingRepo is a mock of SettingRepo interface.
type MockSettingRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSettingRepoMockRecorder
	isgomock struct{}
}

// MockSettingRepoMockRecorder is the mock recorder for MockSettingRepo.
type MockSettingRepoMockRecorder struct {
	mock *MockSettingRepo
}

// NewMockSettingRepo creates a new mock instance.
func NewMockSettingRepo(ctrl *gomock.Controller) *MockSettingRepo {
	mock := &MockSettingRepo{ctrl: ctrl}
	mock.recorder = &MockSettingRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSettingRepo) EXPECT() *MockSettingRepoMockRecorder {
	return m.recorder
}

// Delete mocks base method.
func (m *MockSettingRepo) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSettingRepoMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSettingRepo)(nil).Delete), ctx, key)
}

// Get mocks base method.
func (m *MockSettingRepo) Get(ctx context.Context, key string) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Get indicates an expected call of Get.
func (mr *MockSettingRepoMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockSettingRepo)(nil).Get), ctx, key)
}

// Set mocks base method.
func (m *MockSettingRepo) Set(ctx context.Context, key, value string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockSettingRepoMockRecorder) Set(ctx, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockSettingRepo)(nil).Set), ctx, key, value)
}
