// Code generated by MockGen. DO NOT EDIT.
// Source: token.go
//
// Generated by this command:
//
//	mockgen -source token.go -destination mock/token.go
//

// Package mock_token_repo is a generated GoMock package.
package mock_token_repo

import (
	context "context"
	reflect "reflect"

	token_entity "github.com/opskat/opsnap/internal/model/entity/token_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTokenRepo is a mock of TokenRepo interface.
type MockTokenRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTokenRepoMockRecorder
	isgomock struct{}
}

// MockTokenRepoMockRecorder is the mock recorder for MockTokenRepo.
type MockTokenRepoMockRecorder struct {
	mock *MockTokenRepo
}

// NewMockTokenRepo creates a new mock instance.
func NewMockTokenRepo(ctrl *gomock.Controller) *MockTokenRepo {
	mock := &MockTokenRepo{ctrl: ctrl}
	mock.recorder = &MockTokenRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTokenRepo) EXPECT() *MockTokenRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTokenRepo) Create(ctx context.Context, t *token_entity.Token) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTokenRepoMockRecorder) Create(ctx, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTokenRepo)(nil).Create), ctx, t)
}

// Find mocks base method.
func (m *MockTokenRepo) Find(ctx context.Context, id int64) (*token_entity.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", ctx, id)
	ret0, _ := ret[0].(*token_entity.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find.
func (mr *MockTokenRepoMockRecorder) Find(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockTokenRepo)(nil).Find), ctx, id)
}

// FindByHash mocks base method.
func (m *MockTokenRepo) FindByHash(ctx context.Context, hash string) (*token_entity.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByHash", ctx, hash)
	ret0, _ := ret[0].(*token_entity.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByHash indicates an expected call of FindByHash.
func (mr *MockTokenRepoMockRecorder) FindByHash(ctx, hash any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByHash", reflect.TypeOf((*MockTokenRepo)(nil).FindByHash), ctx, hash)
}

// FindByName mocks base method.
func (m *MockTokenRepo) FindByName(ctx context.Context, name string) ([]*token_entity.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByName", ctx, name)
	ret0, _ := ret[0].([]*token_entity.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByName indicates an expected call of FindByName.
func (mr *MockTokenRepoMockRecorder) FindByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByName", reflect.TypeOf((*MockTokenRepo)(nil).FindByName), ctx, name)
}

// List mocks base method.
func (m *MockTokenRepo) List(ctx context.Context) ([]*token_entity.Token, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx)
	ret0, _ := ret[0].([]*token_entity.Token)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTokenRepoMockRecorder) List(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTokenRepo)(nil).List), ctx)
}

// Revoke mocks base method.
func (m *MockTokenRepo) Revoke(ctx context.Context, id, now int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Revoke", ctx, id, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// Revoke indicates an expected call of Revoke.
func (mr *MockTokenRepoMockRecorder) Revoke(ctx, id, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Revoke", reflect.TypeOf((*MockTokenRepo)(nil).Revoke), ctx, id, now)
}

// TouchLastUsed mocks base method.
func (m *MockTokenRepo) TouchLastUsed(ctx context.Context, id, now int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TouchLastUsed", ctx, id, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// TouchLastUsed indicates an expected call of TouchLastUsed.
func (mr *MockTokenRepoMockRecorder) TouchLastUsed(ctx, id, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TouchLastUsed", reflect.TypeOf((*MockTokenRepo)(nil).TouchLastUsed), ctx, id, now)
}
