// Code generated by MockGen. DO NOT EDIT.
// Source: oidc.go
//
// Generated by this command:
//
//	mockgen -source oidc.go -destination mock/oidc.go
//

// Package mock_oidc_repo is a generated GoMock package.
package mock_oidc_repo

import (
	context "context"
	reflect "reflect"

	oidc_entity "github.com/opskat/opsnap/internal/model/entity/oidc_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCRepo is a mock of OIDCRepo interface.
type MockOIDCRepo struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCRepoMockRecorder
	isgomock struct{}
}

// MockOIDCRepoMockRecorder is the mock recorder for MockOIDCRepo.
type MockOIDCRepoMockRecorder struct {
	mock *MockOIDCRepo
}

// NewMockOIDCRepo creates a new mock instance.
func NewMockOIDCRepo(ctrl *gomock.Controller) *MockOIDCRepo {
	mock := &MockOIDCRepo{ctrl: ctrl}
	mock.recorder = &MockOIDCRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCRepo) EXPECT() *MockOIDCRepoMockRecorder {
	return m.recorder
}

// DeleteBinding mocks base method.
func (m *MockOIDCRepo) DeleteBinding(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteBinding", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteBinding indicates an expected call of DeleteBinding.
func (mr *MockOIDCRepoMockRecorder) DeleteBinding(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteBinding", reflect.TypeOf((*MockOIDCRepo)(nil).DeleteBinding), ctx)
}

// GetBinding mocks base method.
func (m *MockOIDCRepo) GetBinding(ctx context.Context) (*oidc_entity.Binding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBinding", ctx)
	ret0, _ := ret[0].(*oidc_entity.Binding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBinding indicates an expected call of GetBinding.
func (mr *MockOIDCRepoMockRecorder) GetBinding(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBinding", reflect.TypeOf((*MockOIDCRepo)(nil).GetBinding), ctx)
}

// GetProvider mocks base method.
func (m *MockOIDCRepo) GetProvider(ctx context.Context) (*oidc_entity.Provider, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProvider", ctx)
	ret0, _ := ret[0].(*oidc_entity.Provider)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProvider indicates an expected call of GetProvider.
func (mr *MockOIDCRepoMockRecorder) GetProvider(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProvider", reflect.TypeOf((*MockOIDCRepo)(nil).GetProvider), ctx)
}

// SaveBinding mocks base method.
func (m *MockOIDCRepo) SaveBinding(ctx context.Context, b *oidc_entity.Binding) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveBinding", ctx, b)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveBinding indicates an expected call of SaveBinding.
func (mr *MockOIDCRepoMockRecorder) SaveBinding(ctx, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveBinding", reflect.TypeOf((*MockOIDCRepo)(nil).SaveBinding), ctx, b)
}

// SaveProvider mocks base method.
func (m *MockOIDCRepo) SaveProvider(ctx context.Context, p *oidc_entity.Provider) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveProvider", ctx, p)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveProvider indicates an expected call of SaveProvider.
func (mr *MockOIDCRepoMockRecorder) SaveProvider(ctx, p any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveProvider", reflect.TypeOf((*MockOIDCRepo)(nil).SaveProvider), ctx, p)
}
