// Code generated by MockGen. DO NOT EDIT.
// Source: admin.go
//
// Generated by this command:
//
//	mockgen -source admin.go -destination mock/admin.go
//

// Package mock_admin_repo is a generated GoMock package.
package mock_admin_repo

import (
	context "context"
	reflect "reflect"

	admin_entity "github.com/opskat/opsnap/internal/model/entity/admin_entity"
	gomock "go.uber.org/mock/gomock"
)

// MockAdminRepo is a mock of AdminRepo interface.
type MockAdminRepo struct {
	ctrl     *gomock.Controller
	recorder *MockAdminRepoMockRecorder
	isgomock struct{}
}

// MockAdminRepoMockRecorder is the mock recorder for MockAdminRepo.
type MockAdminRepoMockRecorder struct {
	mock *MockAdminRepo
}

// NewMockAdminRepo creates a new mock instance.
func NewMockAdminRepo(ctrl *gomock.Controller) *MockAdminRepo {
	mock := &MockAdminRepo{ctrl: ctrl}
	mock.recorder = &MockAdminRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAdminRepo) EXPECT() *MockAdminRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockAdminRepo) Create(ctx context.Context, admin *admin_entity.Admin) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, admin)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockAdminRepoMockRecorder) Create(ctx, admin any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockAdminRepo)(nil).Create), ctx, admin)
}

// Get mocks base method.
func (m *MockAdminRepo) Get(ctx context.Context) (*admin_entity.Admin, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx)
	ret0, _ := ret[0].(*admin_entity.Admin)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockAdminRepoMockRecorder) Get(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockAdminRepo)(nil).Get), ctx)
}

// UpdatePassword mocks base method.
func (m *MockAdminRepo) UpdatePassword(ctx context.Context, hash string, now int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePassword", ctx, hash, now)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePassword indicates an expected call of UpdatePassword.
func (mr *MockAdminRepoMockRecorder) UpdatePassword(ctx, hash, now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePassword", reflect.TypeOf((*MockAdminRepo)(nil).UpdatePassword), ctx, hash, now)
}
